"""
Canvas fingerprint noise.

Detectors hash the pixel output of a fixed drawing routine. Two rules make
this surface safe:
  1. The output must differ from the raw automation environment (SwiftShader
     renders produce a small set of well-known hashes).
  2. The output must be *stable per profile* — a fingerprint that drifts
     between page loads is itself an automation signal.
So the noise is generated by a deterministic PRNG seeded with
profile.canvas_noise_seed: same profile → same canvas, always.

JS logic extracted verbatim from stealth-kit/src/core/init-scripts/canvas.ts;
the seed is serialized with json.dumps and spliced in place of the
`addInitScript(fn, arg)` mechanism the TS version uses.
"""

import json

from ...fingerprint.profiles import FingerprintProfile

_CANVAS_BODY = r"""
(profile => {
  // mulberry32: tiny, fast, deterministic 32-bit PRNG.
  const mulberry32 = (seed) => {
    let a = seed >>> 0;
    return () => {
      a |= 0;
      a = (a + 0x6d2b79f5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  };

  // Perturb a small, deterministic subset of pixels by ±1 in one channel.
  // Visually invisible, but changes every downstream hash.
  const addNoise = (ctx, x, y, w, h) => {
    if (w <= 0 || h <= 0) return;
    const rand = mulberry32(profile.canvasNoiseSeed);
    const image = ctx.getImageData(x, y, w, h);
    const { data } = image;
    const pixelCount = w * h;
    const touched = Math.max(8, Math.floor(pixelCount / 64));
    for (let i = 0; i < touched; i++) {
      const idx = Math.floor(rand() * pixelCount) * 4 + Math.floor(rand() * 3);
      data[idx] = Math.min(255, Math.max(0, data[idx] + (rand() < 0.5 ? -1 : 1)));
    }
    ctx.putImageData(image, x, y);
  };

  // --- HTMLCanvasElement.toDataURL / toBlob: noise the bitmap before encoding ---
  const originalToDataURL = HTMLCanvasElement.prototype.toDataURL;
  HTMLCanvasElement.prototype.toDataURL = function (...args) {
    const ctx = this.getContext('2d');
    if (ctx) addNoise(ctx, 0, 0, this.width, this.height);
    return originalToDataURL.apply(this, args);
  };

  const originalToBlob = HTMLCanvasElement.prototype.toBlob;
  HTMLCanvasElement.prototype.toBlob = function (...args) {
    const ctx = this.getContext('2d');
    if (ctx) addNoise(ctx, 0, 0, this.width, this.height);
    return originalToBlob.apply(this, args);
  };

  // --- CanvasRenderingContext2D.getImageData: noise reads directly too ---
  const originalGetImageData = CanvasRenderingContext2D.prototype.getImageData;
  CanvasRenderingContext2D.prototype.getImageData = function (sx, sy, sw, sh, ...rest) {
    const image = originalGetImageData.call(this, sx, sy, sw, sh, ...rest);
    const rand = mulberry32(profile.canvasNoiseSeed);
    const { data } = image;
    const pixelCount = sw * sh;
    const touched = Math.max(8, Math.floor(pixelCount / 64));
    for (let i = 0; i < touched; i++) {
      const idx = Math.floor(rand() * pixelCount) * 4 + Math.floor(rand() * 3);
      data[idx] = Math.min(255, Math.max(0, data[idx] + (rand() < 0.5 ? -1 : 1)));
    }
    return image;
  };

  // Keep native-looking toString for the three replaced methods.
  for (const [proto, name] of [
    [HTMLCanvasElement.prototype, 'toDataURL'],
    [HTMLCanvasElement.prototype, 'toBlob'],
    [CanvasRenderingContext2D.prototype, 'getImageData'],
  ]) {
    Object.defineProperty(proto[name], 'toString', {
      value: () => `function ${name}() { [native code] }`,
      configurable: true,
    });
  }
})(__PROFILE__);
"""


def make_canvas_init_script(profile: FingerprintProfile) -> str:
    profile_json = json.dumps({"canvasNoiseSeed": profile.canvas_noise_seed})
    return _CANVAS_BODY.replace("__PROFILE__", profile_json)
